# Generated by Django 4.2.8 on 2023-12-28 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("restapi", "0004_customuser_first_name_customuser_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("time", models.TimeField()),
            ],
            options={
                "ordering": [["day", "time"]],
                "unique_together": {("day", "time")},
            },
        ),
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_scheduler", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "week_day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "month_week",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Third"),
                            (4, "Fourth"),
                            (5, "Last"),
                        ],
                        null=True,
                    ),
                ),
                ("interval", models.IntegerField(default=1)),
                ("end_recurrence", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="MeetingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("description", models.CharField(default="", max_length=1000)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UserDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restapi.eventtime",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "working_days",
                    models.IntegerField(
                        verbose_name=models.IntegerField(
                            blank=True,
                            choices=[
                                (0, "Monday"),
                                (1, "Tuesday"),
                                (2, "Wednesday"),
                                (3, "Thursday"),
                                (4, "Friday"),
                                (5, "Saturday"),
                                (6, "Sunday"),
                            ],
                            null=True,
                        )
                    ),
                ),
                ("working_hours_start", models.TimeField(default="09:00:00")),
                ("working_hours_end", models.TimeField(default="17:00:00")),
            ],
        ),
        migrations.RemoveField(
            model_name="agendaitem",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="answerer",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="asker",
        ),
        migrations.RemoveField(
            model_name="questionanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="attendee",
        ),
        migrations.RemoveField(
            model_name="meeting",
            name="scheduler",
        ),
        migrations.AddField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="meeting",
            name="duration",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="meeting",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
        migrations.DeleteModel(
            name="ActionItem",
        ),
        migrations.DeleteModel(
            name="AgendaItem",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="QuestionAnswer",
        ),
        migrations.AddField(
            model_name="userdigest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="meetingtask",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restapi.meeting"
            ),
        ),
        migrations.AddField(
            model_name="meetingtask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restapi.task"
            ),
        ),
        migrations.AddField(
            model_name="meetingattendee",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restapi.meeting"
            ),
        ),
        migrations.AddField(
            model_name="meetingattendee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="recurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restapi.meetingrecurrence",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingtask",
            unique_together={("meeting", "task")},
        ),
    ]
