# Generated by Django 5.0 on 2023-12-21 20:23

import django.db.models.deletion
import django.utils.timezone
import restapi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_customuser_first_name_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(restapi.models.DaysOfWeek['SUNDAY'], 0), (restapi.models.DaysOfWeek['MONDAY'], 1), (restapi.models.DaysOfWeek['TUESDAY'], 2), (restapi.models.DaysOfWeek['WEDNESDAY'], 3), (restapi.models.DaysOfWeek['THURSDAY'], 4), (restapi.models.DaysOfWeek['FRIDAY'], 5), (restapi.models.DaysOfWeek['SATURDAY'], 6)])),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('working_days', models.IntegerField(verbose_name=models.IntegerField(choices=[(restapi.models.DaysOfWeek['SUNDAY'], 0), (restapi.models.DaysOfWeek['MONDAY'], 1), (restapi.models.DaysOfWeek['TUESDAY'], 2), (restapi.models.DaysOfWeek['WEDNESDAY'], 3), (restapi.models.DaysOfWeek['THURSDAY'], 4), (restapi.models.DaysOfWeek['FRIDAY'], 5), (restapi.models.DaysOfWeek['SATURDAY'], 6)]))),
                ('working_hours_start', models.TimeField(default='09:00:00')),
                ('working_hours_end', models.TimeField(default='17:00:00')),
            ],
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='answerer',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='asker',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='scheduler',
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scheduler', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.meeting')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.eventtime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ActionItem',
        ),
        migrations.DeleteModel(
            name='AgendaItem',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
