version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: agendable_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/dev
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 30s
      start_period: 5s
      retries: 3
    depends_on:
      - redis
      - mailhog
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=agendable
      - POSTGRES_PASSWORD=agendable
      - POSTGRES_DB=agendable_dev
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
  redis:
    image: redis:7-alpine
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: agendable_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/dev
    depends_on:
      web:
        condition: service_healthy
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: agendable_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/dev
    depends_on:
      web:
        condition: service_healthy
  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: agendable_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/dev
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
