version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tete_a_tete_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/dev
    depends_on:
      - redis
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tete_a_tete
      - POSTGRES_PASSWORD=tete_a_tete
      - POSTGRES_DB=tete_a_tete_dev
  redis:
    image: redis:7-alpine
  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tete_a_tete_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/dev
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tete_a_tete_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/dev
    depends_on:
      - redis
      - db
  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tete_a_tete_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/dev
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
