version: '3.8'

services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  ui:
    build: ./ui
    command: npm start
    volumes:
      - ./ui/:/usr/src/ui/
    ports:
      - 3000:3000
    depends_on:
      - app
    profiles:
      - 'frontend'
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tete_a_tete
      - POSTGRES_PASSWORD=tete_a_tete
      - POSTGRES_DB=tete_a_tete_dev

volumes:
  postgres_data:
