# Generated by Django 4.2.8 on 2024-06-22 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingattendee",
            unique_together={("meeting", "user")},
        ),
    ]
