# Generated by Django 4.2.8 on 2024-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_alter_meetingattendee_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
    ]
