#!/bin/bash

set -o errexit
set -o nounset

cd /app/backend

worker_ready() {
    celery -A agendable inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A agendable \
    --broker="${CELERY_BROKER}" \
    flower
