#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A tete_a_tete inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery -A tete_a_tete \
    --broker="${CELERY_BROKER}" \
    flower
