# Generated by Django 4.2.7 on 2023-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='num_reschedules',
            field=models.IntegerField(default=0),
        ),
    ]
