# Generated by Django 4.2.7 on 2023-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('restapi', '0004_user_user_name_alter_user_email_address'), ('restapi', '0005_alter_user_email_address_alter_user_user_name'), ('restapi', '0006_meeting_title')]

    dependencies = [
        ('restapi', '0003_question_alter_actionitem_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
